name: dokan
description: "A assignment project for weDevs."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # icon
  cupertino_icons: ^1.0.6
  icons_plus: ^5.0.0

  # http
  http: ^1.2.1

  # state management
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  # router
  go_router: ^14.1.0

  # bottom navigation bar
  animated_bottom_navigation_bar: ^1.3.3

  # for loading
  flutter_spinkit: ^5.2.1

  # for showing html msg response from api
  flutter_html: ^3.0.0-beta.2

  # utils
  shared_preferences: ^2.2.3
  gap: ^3.0.1
  fpdart: ^1.1.0
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  persistent_header_adaptive: ^2.1.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
